# _____  _____             _    _               
#|  ___||  ___|__ _   ___ | |_ (_)  ___   _ __  
#| |_   | |_  / _` | / __|| __|| | / _ \ | '_ \ 
#|  _|  |  _|| (_| || (__ | |_ | || (_) || | | |
#|_|    |_|   \__,_| \___| \__||_| \___/ |_| |_|
#This plugin was made by Fan. All right reserved

#Provider's: SQLite, MySQL
Provider: SQLite

Factions:
  max-players: 20
  max-ally: 3
  Powers:
    kill-power: +1
    death-power: -1
  Claims:
    max-claim: 5
    blacklist-worlds: []
  Home:
    blacklist-worlds: []
